version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  assignees:
  - ChecksumDev
  labels:
  - dependencies
  versioning-strategy: increase
